name: reporeader
description: "Live GitHub Repo Documentation & File Viewer."
author: "Mindoro Evolution <mindoro.evolution@gmail.com>"
# repository: https://github.com/<your-org>/<repo>  # optional
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  flutter_markdown: ^0.7.3+1
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  webview_flutter: ^4.7.0
  flutter_local_notifications: ^17.2.1
  # Für Offline-Snapshot Dateispeicherung
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Internationalization support
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: "adaptive"
  ios: true
  windows:
    generate: true
    image_path: assets/icons/reporeader_icon.png
    icon_size: 48
  macos:
    generate: true
    image_path: assets/icons/reporeader_icon.png
  web:
    generate: true
    image_path: assets/icons/reporeader_icon.png
    background_color: "#ffffff"
    theme_color: "#ffffff"
  # Basis-Icon (wird für iOS genommen falls kein eigenes image_path_ios angegeben – Plugin verlangt dieses Feld zwingend)
  image_path: assets/icons/reporeader_icon.png
  # Foreground aktuell noch das volle Icon (inkl. Kreis). Später besser eine freigestellte Buch-Grafik verwenden.
  adaptive_icon_foreground: assets/icons/reporeader_icon.png
  # Einfarbiger Hintergrund (stabiler als Gradient, vermeidet doppelte Ränder). Du kannst wieder ein PNG setzen.
  adaptive_icon_background: assets/icons/reporeader_bg.png
  # iOS nutzt ein eigenes (kann identisch sein). Wenn nicht vorhanden: gleiche Datei kopieren.
  image_path_ios: assets/icons/reporeader_icon.png
  remove_alpha_ios: true
  min_sdk_android: 23

